#!/usr/bin/env bash
# scripts/hooks/guard-write.sh
#
# Claude Code PreToolUse filter for Edit / Write / NotebookEdit tools.
# Blocks edits to generated files, secret files, and Copier-managed state.
#
# Exit semantics:
#   0   allow (stderr is informational warnings shown to Claude)
#   2   block — stderr is the reason

set -uo pipefail

input=$(cat)
file_path=$(printf '%s' "$input" | python3 -c '
import json, sys
try:
    d = json.load(sys.stdin)
    fp = d.get("tool_input", {}).get("file_path", "")
    if not fp:
        fp = d.get("tool_input", {}).get("notebook_path", "")
    print(fp)
except Exception:
    print("")
' 2>/dev/null || echo "")

if [ -z "$file_path" ]; then
  exit 0
fi

block() {
  echo "BLOCKED by rl3-templates guard-write: $1" >&2
  echo "Path: $file_path" >&2
  exit 2
}

# Normalise — strip leading ./ and CLAUDE_PROJECT_DIR prefix
proj="${CLAUDE_PROJECT_DIR:-.}"
rel="${file_path#"${proj}"/}"
rel="${rel#./}"
basename=$(basename "$file_path")

case "$rel" in
  # ── Generated by tooling — DO NOT hand-edit ──────────────────────────────
  *routeTree.gen.ts)
    block "routeTree.gen.ts is generated by TanStack Router. Re-run 'pnpm dev' to regenerate." ;;

  frontend/src/client/* | */frontend/src/client/*)
    block "frontend/src/client/ is the generated SDK (@hey-api/openapi-ts). Run 'pnpm exec openapi-ts' to regenerate." ;;
esac

case "$basename" in
  *_pb2.py | *_pb2.pyi | *_pb2_grpc.py)
    block "Protobuf generated files. Regenerate from the .proto source." ;;

  uv.lock | pnpm-lock.yaml | package-lock.json | yarn.lock | bun.lock | Cargo.lock | poetry.lock)
    block "Lockfiles are managed by the package manager. Use 'uv add', 'pnpm add', 'cargo add', etc." ;;

  .copier-answers.yml)
    block ".copier-answers.yml is managed by Copier. Run 'copier update' to refresh template." ;;
esac

# ── Secrets / credential files ─────────────────────────────────────────────
case "$basename" in
  .env | .envrc)
    block "Editing $basename is forbidden. Use .env.example for the committed template." ;;

  .env.local | .env.development | .env.production | .env.staging | .env.test)
    block "Editing $basename is forbidden. .env.example is the only env file in git." ;;
esac

case "$basename" in
  *.pem | *.key | *.p12 | *.pfx | *.jks | *.keystore)
    block "Private keys, certificates, and credentials must never be committed." ;;

  id_rsa | id_dsa | id_ecdsa | id_ed25519)
    block "SSH private keys must never be committed." ;;
esac

# ── Warning-only (exit 0 — Claude sees the warning) ────────────────────────
case "$rel" in
  docs/adr/*.md | */docs/adr/*.md)
    echo "WARN: ADR files are append-only. To supersede a decision, create a new ADR with status 'Supersedes ADR-NNN' instead of editing this one." >&2 ;;
esac

case "$basename" in
  pyproject.toml)
    echo "WARN: when adding dependencies to pyproject.toml, prefer 'uv add <pkg>' which updates uv.lock atomically." >&2 ;;

  package.json)
    echo "WARN: when adding dependencies to package.json, prefer 'pnpm add <pkg>' which updates pnpm-lock.yaml atomically." >&2 ;;
esac

exit 0
